#!/bin/sh
set -e

if [ "$1" = "purge" ]; then
    if [ -f /etc/sudoers.d/wgmanagement-wireguard-install ]; then
        rm -f /etc/sudoers.d/wgmanagement-wireguard-install
    fi
    if getent passwd wgmanagement >/dev/null 2>&1; then
        userdel wgmanagement
    fi
fi

exit 0
